Modal
ShoTuPalush/project-team-15-htmlcss pull request #3
Opened 2023-06-30 22:13 UTC by SKhrebtan

Перший варіант модалки

2023-07-01 16:58 UTC, ShoTuPalush requested changes
Відписав в тг

2023-07-01 21:40 UTC, SKhrebtan commented
Привіт. модалку я підправив, там патерни, вони вимагають заповнити кожне поле окрім текстеріа в потрібному форматі.
Сворив дів, кинув туди заголовок, текст і фото, зробив розмітку, натискаєш все працює, але валідатор викинув ерор, що не можна в лейбл дів кидати, я дістав з діву все, знов ерор, що не можна заголовок і т. д.
Так, що повернув як було, через js можу зробити, щоб клацаєш в будьяке місце(ліст-айтем) і буде чекед. бо так працювало на сам лейбл, заголовок текст і фото, а на все інше місце фону ні.
Додав ховер чекбоксам при десктопі і додав інпутам форми забарвлення в оранж при фокусі і фокус ховер кнпоці сабміт

2023-07-01 21:56 UTC, ShoTuPalush requested changes
Чекбокси і валідація номера

2023-07-02 06:50 UTC, SKhrebtan commented
Привіт. Курсор поінтер на лейбли додав, зробив js по кліку на картку ставив/знімав статус чекед (в main.js). На рахунок патерну, там картка, а не телефон, просто тайп телефон - паттерн приймає тільки цифри від 13 до 19.

2023-07-02 06:52 UTC, SKhrebtan commented
Після того, як гілка модал буде прийнята я дороблю кнопку догори, бо там вже буде конфлікт в main.js

2023-07-02 07:50 UTC, SKhrebtan commented
Ще можливо на list-item (картку) додати теж курсор поінтер для кращого user experience?

2023-07-02 08:09 UTC, ShoTuPalush commented
> Привіт. Курсор поінтер на лейбли додав, зробив js по кліку на картку ставив/знімав статус чекед (в main.js). На рахунок патерну, там картка, а не телефон, просто тайп телефон - паттерн приймає тільки цифри від 13 до 19, тому поки що нічого не змінював

main.js краще не редагувати. Я би скорше створював окремий js в папці js і підключав їх

2023-07-02 08:14 UTC, ShoTuPalush commented
> Ще можливо на list-item (картку) додати теж курсор поінтер для кращого user experience?

якраз в list-item треба доодати курсор поінтер, а от в інпутах не потрібно

2023-07-03 08:45 UTC, SKhrebtan commented
Вкинув ul to form та зробив , щоб ховер на чекбоксі був при наведенні на всю картку, так само як Ви радили зробити курсор поінтер, тобто при наведенні в будя-якому місці картки буде курсор поінтер і аутлайн на чебоксі.
Я правильно зрозумів, коли Ви змерджете фото і вари, то я пулю собі зміни прямо в свою гілку модал?

2023-07-03 13:20 UTC, SKhrebtan commented
Я змінив назви 4 фото, там були пробіли перед дефісом, ще не розумів чого фото не грузяться. І я додав в спрайт свої свг, бо я там робив по-новому, не так я на курсі було, я там два юзи в один свг кинув (плюс не дуже хочеться все перероблювати, воно норм працює).

2023-07-03 17:01 UTC, ShoTuPalush commented
в тебе все готово? лиш зміні?

2023-07-03 18:03 UTC, SKhrebtan commented
так, зараз роблю. Я б ще це 250ms linear в вари додав

2023-07-03 18:30 UTC, SKhrebtan commented
Вари додав, повторювальні стилі прибрав, наче все.   .backdrop is-hidden я закоментував(там воно зверху css), щоб одразу видно було модалку

2023-07-03 19:37 UTC, ShoTuPalush commented
все супер, модалку замержу коли буде хотяби одна секція з кнопкою

2023-07-03 19:47 UTC, ShoTuPalush commented
є помилки в валідаторі

2023-07-04 05:27 UTC, SKhrebtan commented
Виправив, залишились помилки типу нема хеду та доктайпу

2023-07-04 09:43 UTC, SKhrebtan commented
Оновився з мейну, змінив шляхи до фото. Але знов таки, змінив назви фото vegetables-basket -tablet.png і інші, де були пробіли перед дефісом

2023-07-04 10:19 UTC, ShoTuPalush commented
бачу, вже процесі буду вирішувати. все добре

2023-07-04 10:19 UTC, ShoTuPalush approved these changes
Good

2023-07-04 12:53 UTC, merged