Added vegetables.html with markup, added vegetables.html to index.html
ShoTuPalush/project-team-15-htmlcss pull request #4
Opened 2023-07-01 17:21 UTC by PavelZavadskiy

2023-07-01 17:59 UTC, ShoTuPalush requested changes
в мене выдсутні стилі

2023-07-01 18:22 UTC, PavelZavadskiy commented
> в мене відсутні стилі

Це гілка тільки для розмітки html

2023-07-01 18:28 UTC, ShoTuPalush commented
більшість роблять все зразу в одній гілці

2023-07-01 20:11 UTC, PavelZavadskiy commented
> більшість роблять все зразу в одній гілці. Ти будеш окремо робити?

Не проблема. Зроблю в одній. В мене вже є css частина. Тільки є запитання, написав в слак

2023-07-01 20:13 UTC, ShoTuPalush commented
> > більшість роблять все зразу в одній гілці. Ти будеш окремо робити?
> 
> Не проблема. Зроблю в одній. В мене вже є css частина. Тільки є запитання, написав в слак

Яке питання?

2023-07-04 11:58 UTC, ShoTuPalush approved these changes
Все добре. Тільки валідатор видає помилки з текст шадов. Я це можу самий виправити

2023-07-04 12:32 UTC, merged