We will call you
ShoTuPalush/project-team-15-htmlcss pull request #5
Opened 2023-07-02 12:06 UTC by ilnickii

Тут все окрім картинок.

2023-07-02 12:51 UTC, ShoTuPalush requested changes
Колір border в інпуті повинен бути #C1BDBD. В інпуті немає валідації, потрібно простенький. І я би ще поставив required. На рахунок переходів, мій косяк, забув повідомити.

2023-07-02 14:32 UTC, ilnickii commented
Виправив і додав все з ваших зауважень

2023-07-02 16:12 UTC, ShoTuPalush requested changes
Валідатор видав помилки https://prnt.sc/ZicPVMLSRqdt
Потірбно забрати ці значення https://prnt.sc/wd2yJmrcJGhP

2023-07-02 18:11 UTC, ilnickii commented
Зроблено

2023-07-03 17:32 UTC, ilnickii commented
додав картинки

2023-07-03 18:28 UTC, ShoTuPalush commented
Змінні не будеш використовувати? У всіх секціях пише, що картинка має бути контента, а в тебе ні. Як думаєш це опечатка? Чи краще зробити як контенту?

2023-07-04 16:31 UTC, ilnickii commented
Додав змінні і картинки контентні

2023-07-04 17:41 UTC, ilnickii commented
Я все доробив повністю.

2023-07-05 10:32 UTC, ShoTuPalush approved these changes
good

2023-07-05 10:32 UTC, merged